# Book settings
title: Repositorio de PAD
author: equipo docente LCA.
logo: _static/logo-uniandes.png

repository:
  url: https://github.com/copa-uniandes/PAD-web-tutorials
  path_to_book: PAD-book
  branch: main

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: _static/icon.png
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: false
  extra_navbar: "" #Removes 'Powered by Jupyter Book' from left navbar.
  pdf_viewer: true   # Add this line to enable PDF links to open in the book

myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

execute:
#  execute_notebooks: "off"
  execute_notebooks: force
  allow_errors: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
